/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.0 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "ADC.h"
#include "ADC_Mux.h"
#include "I2C.h"
#include "I2C_PVT.h"
#include "DB_aliases.h"
#include "D10_Ctrl.h"
#include "D11_Ctrl.h"
#include "SPIM_0.h"
#include "SPIM_0_PVT.h"
#include "PRS.h"
#include "ToneTimer.h"
#include "Micros_Counter.h"
#include "Tone_Interrupt.h"
#include "Millis_Counter.h"
#include "Clock_3.h"
#include "I2C_Enable.h"
#include "USBUART.h"
#include "USBUART_audio.h"
#include "USBUART_cdc.h"
#include "USBUART_hid.h"
#include "USBUART_midi.h"
#include "USBUART_pvt.h"
#include "UART.h"
#include "UART_Clock.h"
#include "HW_INT.h"
#include "SPI_Clock_In.h"
#include "SPIM_1.h"
#include "SPIM_1_PVT.h"
#include "SPI_Mode_Reg.h"
#include "P0_aliases.h"
#include "P3_aliases.h"
#include "P4_aliases.h"
#include "P5_aliases.h"
#include "P12_aliases.h"
#include "UserButton_aliases.h"
#include "UserButton.h"
#include "A_aliases.h"
#include "DA_aliases.h"
#include "DA.h"
#include "ServoInterrupt.h"
#include "Clock_12.h"
#include "ServoCounter.h"
#include "BootloaderResetTimer.h"
#include "BootloaderResetInterrupt.h"
#include "Clock_2.h"
#include "PWM_3.h"
#include "PWM_2.h"
#include "Clock_5.h"
#include "PWM_1.h"
#include "Bootloadable.h"
#include "ADC_IRQ.h"
#include "ADC_theACLK.h"
#include "USBUART_Dm_aliases.h"
#include "USBUART_Dm.h"
#include "USBUART_Dp_aliases.h"
#include "USBUART_Dp.h"
#include "core_cm3_psoc5.h"
#include "core_cm3.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"

/*[]*/

