/* definitions generated by preprocessor, copy into defines.h */
#ifndef	PPINC
#define	_ATMEGA3290	// device select: _ATMEGAxxxx
#define	_B2048	// boot size select: _Bxxxx (words), powers of two only
#ifdef	__ICCAVR__
#include	"iom3290.h"
#endif
#if	__GNUC__
#include	<avr/io.h>
#endif

/* define pin for enter-self-prog-mode */
#define	PROGPORT	PORTD
#define	PROGPIN	PIND
#define	PROG_NO	PD4

/* baud rate register value calculation */
#define	CPU_FREQ	8000000
#define	BAUD_RATE	9600
#define	BRREG_VALUE	51

/* definitions for UART control */
#define	BAUD_RATE_LOW_REG	UBRR
#define	UART_CONTROL_REG	UCSRB
#define	ENABLE_TRANSMITTER_BIT	TXEN
#define	ENABLE_RECEIVER_BIT	RXEN
#define	UART_STATUS_REG	UCSRA
#define	TRANSMIT_COMPLETE_BIT	TXC
#define	RECEIVE_COMPLETE_BIT	RXC
#define	UART_DATA_REG	UDR

/* definitions for SPM control */
#define	SPMCR_REG	SPMCSR
#define	PAGESIZE	128
#define	APP_END	28672
//#define	LARGE_MEMORY

/* definitions for device recognition */
#define	PARTCODE	
#define	SIGNATURE_BYTE_1	0x1E
#define	SIGNATURE_BYTE_2	0x95
#define	SIGNATURE_BYTE_3	0x04

/* indicate that preprocessor result is included */
#define	PPINC
#endif
